global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "fastapi_plantilla"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "api:8000"
          - "host.docker.internal:8000"
