"""initial_schema.

Revision ID: ffab4e4ee76c
Revises:
Create Date: 2026-09-13 16:54:56.126659

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ffab4e4ee76c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "TRASHED",
                "INACTIVE",
                "ARCHIVED",
                "SUSPENDED",
                name="recordstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("restored_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_users_email"), "auth_users", ["email"], unique=True)
    op.create_index(
        op.f("ix_auth_users_is_active"), "auth_users", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_auth_users_status"), "auth_users", ["status"], unique=False
    )
    op.create_table(
        "auth_verifications",
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auth_verifications_identifier_value",
        "auth_verifications",
        ["identifier", "value"],
        unique=False,
    )
    op.create_table(
        "rbac_roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "TRASHED",
                "INACTIVE",
                "ARCHIVED",
                "SUSPENDED",
                name="recordstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("restored_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rbac_roles_slug_active",
        "rbac_roles",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.create_index(
        op.f("ix_rbac_roles_status"), "rbac_roles", ["status"], unique=False
    )
    op.create_table(
        "sys_audit_logs",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=True),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sys_audit_logs_action"), "sys_audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_sys_audit_logs_actor_id"), "sys_audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_audit_logs_created_at"),
        "sys_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_audit_logs_entity_id"),
        "sys_audit_logs",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_audit_logs_entity_type"),
        "sys_audit_logs",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "sys_modules",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "category", sa.String(length=50), server_default="system", nullable=False
        ),
        sa.Column("category_name", sa.String(length=100), nullable=True),
        sa.Column("category_icon", sa.String(length=50), nullable=True),
        sa.Column(
            "category_order", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "is_trasheable",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "is_exportable",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_modules_code"), "sys_modules", ["code"], unique=True)
    op.create_index(
        op.f("ix_sys_modules_is_active"), "sys_modules", ["is_active"], unique=False
    )
    op.create_table(
        "auth_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "account_id", name="uq_provider_account"),
    )
    op.create_index(
        op.f("ix_auth_accounts_user_id"), "auth_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("impersonated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["impersonated_by"], ["auth_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"),
        "auth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_impersonated_by"),
        "auth_sessions",
        ["impersonated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_is_valid"), "auth_sessions", ["is_valid"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_token"), "auth_sessions", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("nif", sa.String(length=50), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "TRASHED",
                "INACTIVE",
                "ARCHIVED",
                "SUSPENDED",
                name="recordstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("restored_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(
        "ix_companies_nif_active",
        "companies",
        ["nif"],
        unique=True,
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.create_index(
        op.f("ix_companies_owner_id"), "companies", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_companies_sector"), "companies", ["sector"], unique=False)
    op.create_index(op.f("ix_companies_status"), "companies", ["status"], unique=False)
    op.create_table(
        "rbac_role_assignments",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["rbac_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "entity_type", "entity_id", name="uq_role_assignment"
        ),
    )
    op.create_index(
        op.f("ix_rbac_role_assignments_entity_id"),
        "rbac_role_assignments",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rbac_role_assignments_entity_type"),
        "rbac_role_assignments",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rbac_role_assignments_role_id"),
        "rbac_role_assignments",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "rbac_role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "READ",
                "UPDATE",
                "DELETE",
                "RESTORE",
                "EXPORT",
                "IMPORT",
                "SETTINGS",
                name="rbacactions",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum(
                "GLOBAL", "TEAM", "OWN", name="scopetype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["module_id"], ["sys_modules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["rbac_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "module_id", "action", name="uq_role_permission_action"
        ),
    )
    op.create_index(
        op.f("ix_rbac_role_permissions_module_id"),
        "rbac_role_permissions",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rbac_role_permissions_role_id"),
        "rbac_role_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "sys_storage",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("extension", sa.String(length=20), nullable=True),
        sa.Column("is_uploaded", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "TRASHED",
                "INACTIVE",
                "ARCHIVED",
                "SUSPENDED",
                name="recordstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("restored_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sys_storage_entity",
        "sys_storage",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_storage_entity_id"), "sys_storage", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_storage_entity_type"),
        "sys_storage",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_storage_file_key"), "sys_storage", ["file_key"], unique=True
    )
    op.create_index(
        op.f("ix_sys_storage_is_uploaded"),
        "sys_storage",
        ["is_uploaded"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_storage_owner_id"), "sys_storage", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_storage_status"), "sys_storage", ["status"], unique=False
    )
    op.create_table(
        "sys_teams",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING",
                "TRASHED",
                "INACTIVE",
                "ARCHIVED",
                "SUSPENDED",
                name="recordstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("restored_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sys_teams_owner_id"), "sys_teams", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_sys_teams_slug_active",
        "sys_teams",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.create_index(op.f("ix_sys_teams_status"), "sys_teams", ["status"], unique=False)
    op.create_table(
        "sys_trash_bin",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target_entity_type", sa.String(length=50), nullable=True),
        sa.Column("target_entity_id", sa.Uuid(), nullable=True),
        sa.Column("target_entity_name", sa.String(length=255), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_id", name="uq_sys_trash_bin_entity"),
    )
    op.create_index(
        op.f("ix_sys_trash_bin_entity_id"), "sys_trash_bin", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_trash_bin_entity_type"),
        "sys_trash_bin",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_trash_bin_expires_at"),
        "sys_trash_bin",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_trash_bin_owner_id"), "sys_trash_bin", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_sys_trash_bin_target_entity",
        "sys_trash_bin",
        ["target_entity_type", "target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_trash_bin_target_entity_id"),
        "sys_trash_bin",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_trash_bin_target_entity_type"),
        "sys_trash_bin",
        ["target_entity_type"],
        unique=False,
    )
    op.create_table(
        "sys_team_users",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["rbac_roles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["sys_teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_user"),
    )
    op.create_index(
        op.f("ix_sys_team_users_role_id"), "sys_team_users", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_team_users_team_id"), "sys_team_users", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_team_users_user_id"), "sys_team_users", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_team_users_user_id"), table_name="sys_team_users")
    op.drop_index(op.f("ix_sys_team_users_team_id"), table_name="sys_team_users")
    op.drop_index(op.f("ix_sys_team_users_role_id"), table_name="sys_team_users")
    op.drop_table("sys_team_users")
    op.drop_index(
        op.f("ix_sys_trash_bin_target_entity_type"), table_name="sys_trash_bin"
    )
    op.drop_index(op.f("ix_sys_trash_bin_target_entity_id"), table_name="sys_trash_bin")
    op.drop_index("ix_sys_trash_bin_target_entity", table_name="sys_trash_bin")
    op.drop_index(op.f("ix_sys_trash_bin_owner_id"), table_name="sys_trash_bin")
    op.drop_index(op.f("ix_sys_trash_bin_expires_at"), table_name="sys_trash_bin")
    op.drop_index(op.f("ix_sys_trash_bin_entity_type"), table_name="sys_trash_bin")
    op.drop_index(op.f("ix_sys_trash_bin_entity_id"), table_name="sys_trash_bin")
    op.drop_table("sys_trash_bin")
    op.drop_index(op.f("ix_sys_teams_status"), table_name="sys_teams")
    op.drop_index(
        "ix_sys_teams_slug_active",
        table_name="sys_teams",
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.drop_index(op.f("ix_sys_teams_owner_id"), table_name="sys_teams")
    op.drop_table("sys_teams")
    op.drop_index(op.f("ix_sys_storage_status"), table_name="sys_storage")
    op.drop_index(op.f("ix_sys_storage_owner_id"), table_name="sys_storage")
    op.drop_index(op.f("ix_sys_storage_is_uploaded"), table_name="sys_storage")
    op.drop_index(op.f("ix_sys_storage_file_key"), table_name="sys_storage")
    op.drop_index(op.f("ix_sys_storage_entity_type"), table_name="sys_storage")
    op.drop_index(op.f("ix_sys_storage_entity_id"), table_name="sys_storage")
    op.drop_index("ix_sys_storage_entity", table_name="sys_storage")
    op.drop_table("sys_storage")
    op.drop_index(
        op.f("ix_rbac_role_permissions_role_id"), table_name="rbac_role_permissions"
    )
    op.drop_index(
        op.f("ix_rbac_role_permissions_module_id"), table_name="rbac_role_permissions"
    )
    op.drop_table("rbac_role_permissions")
    op.drop_index(
        op.f("ix_rbac_role_assignments_role_id"), table_name="rbac_role_assignments"
    )
    op.drop_index(
        op.f("ix_rbac_role_assignments_entity_type"), table_name="rbac_role_assignments"
    )
    op.drop_index(
        op.f("ix_rbac_role_assignments_entity_id"), table_name="rbac_role_assignments"
    )
    op.drop_table("rbac_role_assignments")
    op.drop_index(op.f("ix_companies_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_sector"), table_name="companies")
    op.drop_index(op.f("ix_companies_owner_id"), table_name="companies")
    op.drop_index(
        "ix_companies_nif_active",
        table_name="companies",
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_is_valid"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_impersonated_by"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_auth_accounts_user_id"), table_name="auth_accounts")
    op.drop_table("auth_accounts")
    op.drop_index(op.f("ix_sys_modules_is_active"), table_name="sys_modules")
    op.drop_index(op.f("ix_sys_modules_code"), table_name="sys_modules")
    op.drop_table("sys_modules")
    op.drop_index(op.f("ix_sys_audit_logs_entity_type"), table_name="sys_audit_logs")
    op.drop_index(op.f("ix_sys_audit_logs_entity_id"), table_name="sys_audit_logs")
    op.drop_index(op.f("ix_sys_audit_logs_created_at"), table_name="sys_audit_logs")
    op.drop_index(op.f("ix_sys_audit_logs_actor_id"), table_name="sys_audit_logs")
    op.drop_index(op.f("ix_sys_audit_logs_action"), table_name="sys_audit_logs")
    op.drop_table("sys_audit_logs")
    op.drop_index(op.f("ix_rbac_roles_status"), table_name="rbac_roles")
    op.drop_index(
        "ix_rbac_roles_slug_active",
        table_name="rbac_roles",
        postgresql_where=sa.text("status != 'TRASHED'"),
        sqlite_where=sa.text("status != 'TRASHED'"),
    )
    op.drop_table("rbac_roles")
    op.drop_index(
        "ix_auth_verifications_identifier_value", table_name="auth_verifications"
    )
    op.drop_table("auth_verifications")
    op.drop_index(op.f("ix_auth_users_status"), table_name="auth_users")
    op.drop_index(op.f("ix_auth_users_is_active"), table_name="auth_users")
    op.drop_index(op.f("ix_auth_users_email"), table_name="auth_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
